apiVersion: v1
kind: Namespace
metadata:
  name: ardan-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ardan-service-pod # Base POD name
  namespace: ardan-service
spec:
  selector:
    matchLabels:
      app: ardan-service # Selector for POD name search.
  template:
    metadata:
      labels:
        app: ardan-service
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: ardan-service
        image: kdykrg/ardan-service:1.01
        imagePullPolicy: Always