apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ./sales-api-patch.yaml
images:
- name: sales-api-image
  newName: kdykrg/sales-api
  newTag: "1.0"
