apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api-pod # Base POD name
  namespace: sales-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sales-api # Selector for POD name search.
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
      - name: sales-api
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"